### ISSUE TITLE
Tables row border is not visible

### ISSUE THREAD

**Issue by JuliusRuppert** [DominoKit/domino-ui#1036]
**Describe the bug**
In domino-ui.css there is the following css selector that defines borders for the table rows.
```css
.dui-datatable-td:not(:last-child) {
    border-bottom: 1px solid var(--dui-datatable-border-color);
}
```
It seems that the selector should be `.dui-datatable-td:not(:last-child)` instead of `.dui-datatable-row:not(:last-child)` to be applied.
