### ISSUE TITLE
Fixed DataTables headers do not align with tbody cells

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#734]
In RC14, a fixed DataTable header will not align with the cells in the body.   It appears that the thead>tr style is still setting width to 100%.

Quick fix is to include this css (or something similar):
```css
.table-fixed .table .thead-fixed > tr,
.table-fixed .table .thead-fixed > tr.data-table-group-row {
  width: initial;
}
```

or... just remove the `width: 100%` from the fixed table thead tr.   Whichever way works.

*Screenshot:*
<img width="871" alt="image" src="https://user-images.githubusercontent.com/861908/204812420-c7b4de2d-25d9-46f0-a321-99973c49cb51.png">
